chore: move contents of explorer to top level (#4230)
DataBiosphere/data-browser pull request #4242
Opened 2024-11-08 01:00 UTC by hunterckx

Note: I wasn't really sure what do with the `scripts` directory that was already at the top level; I've renamed it to `meta-scripts` but I'm not sure if that's the best name

2024-11-08 23:00 UTC, NoopDog commented
@hunterckx meta-scripts can be deleted. It's obsolete.

2024-11-09 02:21 UTC, hannes-ucsc requested changes, later dismissed

2024-11-09 02:21 UTC, hannes-ucsc commented on .gitlab/fragments/explorer/build.yaml
> +  - tar -cvj -f ./.gitlab/distribution.tar.bz2 out
```suggestion
  - tar -cvj -f .gitlab/distribution.tar.bz2 out
```

2024-11-09 03:20 UTC, NoopDog approved these changes

2024-11-09 04:06 UTC, merged